#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
# yabai -m config mouse_follows_focus on
yabai -m config focus_follows_mouse autofocus

yabai -m config window_placement second_child
yabai -m config window_topmost on
yabai -m config window_border on
yabai -m config window_border_blur off
yabai -m config insert_feedback_color 0xff458588
yabai -m config active_window_border_color 0xfffb4934
yabai -m config normal_window_border_color 0xff928374

yabai -m config split_ratio 0.50
yabai -m config auto_balance on

yabai -m config mouse_action1 move
# resize windows if resized with mouse
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action swap

# general space settings
yabai -m config layout bsp
yabai -m config top_padding 5
yabai -m config bottom_padding 5
yabai -m config left_padding 5
yabai -m config right_padding 5
yabai -m config window_gap 06
yabai -m config window_border_width 3
yabai -m config external_bar all:32:0
# yabai -m rule --add app="^Arc$" title="^$" mouse_follows_focus=off
yabai -m rule --add app="^Arc$" title="^$" mouse_follows_focus=off
